apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: pm-saas
type: Opaque
stringData:
  SESSION_SECRET: "session_secret_key"
  SESSION_EXPIRES_IN: "1d"
  GOOGLE_CLIENT_ID: "YOUR_GOOGLE_CLIENT_ID"
  GOOGLE_CLIENT_SECRET: "YOUR_GOOGLE_CLIENT_SECRET"
  GOOGLE_CALLBACK_URL: "CHANGE_ME"


  MONGO_URI: "YOUR_MONGO_URI"